name: twitter-api

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 35.223.45.220 >> ~/.ssh/known_hosts

      - name: Execute deployment script via SSH
        run: |
          scp -i ~/.ssh/id_ed25519 ./build.sh rrafids@35.223.45.220:/home/rrafids/twitter-api/build.sh
          ssh -i ~/.ssh/id_ed25519 rrafids@35.223.45.220 'bash /home/rrafids/twitter-api/build.sh'