name: twitter-api

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '35.223.45.220'
          username: 'rrafids'
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Fix permissions
            sudo chown -R rrafids:rrafids /home/rrafids/twitter-api
            sudo chmod -R u+rwX /home/rrafids/twitter-api

            # Change to the project directory and execute the build script
            cd /home/rrafids/twitter-api
            sudo chmod +x ./build.sh
            sudo ./build.sh
