name: twitter-api

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '35.223.45.220'
          username: 'root'
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /home/rrafids/twitter-api

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            source ~/.bashrc
            nvm install node
            sudo npm install -g pm2

            # Change to the project directory and execute the build script
            cd /home/rrafids/twitter-api
            chmod +x ./build.sh
            ./build.sh
