name: twitter-api

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 35.223.45.220 >> ~/.ssh/known_hosts

      - name: Execute deployment script via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 rrafids@35.223.45.220 << 'EOF'
          cd /home/rrafids/twitter-api
          git pull origin master
          pm2 delete twitter-api
          pm2 start server.js -n twitter-api
          EOF
